spring:
  application:
    name: add-service
server:
  port: 8081

grpc:
  server:
    port: 9090

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: false
